version: "3"

services:

  # Marvel app
  app:

    # Name of tag to be created when building
    image: marvel-xendit

    # Build config
    build:
      context: .

    # Port to expose
    ports:
      - 8080:8080

  # Swagger Server
  doc:

    # Go Swagger
    image: quay.io/goswagger/swagger

    volumes:
      - ./swagger.yaml:/app/swagger.yaml
    working_dir: /app
    #command: generate server -A todo-list -f ./swagger.yaml
    command: serve ./swagger.yaml --no-open --port=8081 --flavor=swagger
    ports:
      - 8081:8081
